import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const publicDir = path.join(root, 'public');
const tsOutputPath = path.join(root, 'src', 'data', 'assetImages.ts');
const jsonOutputPath = path.join(root, 'src', 'data', 'assetImages.json');

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.gif', '.webp', '.svg', '.JPG', '.JPEG', '.PNG', '.ico']);

const SKIP_FILES = new Set(['placeholder.svg', 'favicon.ico']);
const SKIP_DIRS = new Set(['Praxisbilder']);

function walkDir(dir, baseDir = '') {
  const images = [];
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return images;
  }
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relativePath = baseDir ? `${baseDir}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) {
        images.push(...walkDir(fullPath, relativePath));
      }
    } else if (IMAGE_EXTS.has(path.extname(entry.name))) {
      if (SKIP_FILES.has(entry.name)) continue;
      if (entry.name.startsWith('.')) continue;
      images.push({
        filePath: '/' + relativePath.replace(/\\/g, '/'),
        fileName: entry.name,
        ext: path.extname(entry.name),
        size: fs.statSync(fullPath).size,
      });
    }
  }
  return images;
}

const allImages = walkDir(publicDir);
allImages.sort((a, b) => a.filePath.localeCompare(b.filePath));

const data = {
  generatedAt: new Date().toISOString(),
  count: allImages.length,
  images: allImages,
};

// Write .ts file for TypeScript import
const tsContent = `// Auto-generated by scripts/scan-images.mjs — do not edit manually
// Generated: ${data.generatedAt}

export interface ScannedImage {
  filePath: string;
  fileName: string;
  ext: string;
  size: number;
}

export interface AssetImageScan {
  generatedAt: string;
  count: number;
  images: ScannedImage[];
}

const assetImages: AssetImageScan = ${JSON.stringify(data, null, 2)};

export default assetImages;
`;

// Write .json for reference/debugging
fs.mkdirSync(path.dirname(tsOutputPath), { recursive: true });
fs.mkdirSync(path.dirname(jsonOutputPath), { recursive: true });
fs.writeFileSync(tsOutputPath, tsContent);
fs.writeFileSync(jsonOutputPath, JSON.stringify(data, null, 2));
console.log(`✅ Scan complete: ${allImages.length} project images found`);
