// Auto-generated by scripts/scan-images.mjs — do not edit manually
// Generated: 2026-06-29T08:40:14.571Z

export interface ScannedImage {
  filePath: string;
  fileName: string;
  ext: string;
  size: number;
}

export interface AssetImageScan {
  generatedAt: string;
  count: number;
  images: ScannedImage[];
}

const assetImages: AssetImageScan = {
  "generatedAt": "2026-06-29T08:40:14.571Z",
  "count": 55,
  "images": [
    {
      "filePath": "/90_days_fertility_hero.png",
      "fileName": "90_days_fertility_hero.png",
      "ext": ".png",
      "size": 731049
    },
    {
      "filePath": "/akupunktur_hero.png",
      "fileName": "akupunktur_hero.png",
      "ext": ".png",
      "size": 665482
    },
    {
      "filePath": "/akupunktur-behandlung.png",
      "fileName": "akupunktur-behandlung.png",
      "ext": ".png",
      "size": 139279
    },
    {
      "filePath": "/akupunktur-modell.png",
      "fileName": "akupunktur-modell.png",
      "ext": ".png",
      "size": 198665
    },
    {
      "filePath": "/akutaping-nacken.png",
      "fileName": "akutaping-nacken.png",
      "ext": ".png",
      "size": 120485
    },
    {
      "filePath": "/akutaping-schwangerschaft.png",
      "fileName": "akutaping-schwangerschaft.png",
      "ext": ".png",
      "size": 94157
    },
    {
      "filePath": "/ama-divers.jpg",
      "fileName": "ama-divers.jpg",
      "ext": ".jpg",
      "size": 420796
    },
    {
      "filePath": "/angela_deschner.png",
      "fileName": "angela_deschner.png",
      "ext": ".png",
      "size": 733140
    },
    {
      "filePath": "/angela_portrait.png",
      "fileName": "angela_portrait.png",
      "ext": ".png",
      "size": 674534
    },
    {
      "filePath": "/assets/Atmungskette.jpg",
      "fileName": "Atmungskette.jpg",
      "ext": ".jpg",
      "size": 34510
    },
    {
      "filePath": "/assets/BHI Manovska IHT.JPG",
      "fileName": "BHI Manovska IHT.JPG",
      "ext": ".JPG",
      "size": 78197
    },
    {
      "filePath": "/assets/blood-test-21.jpg",
      "fileName": "blood-test-21.jpg",
      "ext": ".jpg",
      "size": 5384523
    },
    {
      "filePath": "/assets/brainlight-system.jpg",
      "fileName": "brainlight-system.jpg",
      "ext": ".jpg",
      "size": 113601
    },
    {
      "filePath": "/assets/Gemini_Generated_Image_r0nb0cr0nb0cr0nb.png",
      "fileName": "Gemini_Generated_Image_r0nb0cr0nb0cr0nb.png",
      "ext": ".png",
      "size": 2396880
    },
    {
      "filePath": "/assets/Hero Zellkraft Kompass.jpg",
      "fileName": "Hero Zellkraft Kompass.jpg",
      "ext": ".jpg",
      "size": 138664
    },
    {
      "filePath": "/assets/IHHT 1 Schwangere.png",
      "fileName": "IHHT 1 Schwangere.png",
      "ext": ".png",
      "size": 167928
    },
    {
      "filePath": "/assets/IHHT 2 Schwangere.png",
      "fileName": "IHHT 2 Schwangere.png",
      "ext": ".png",
      "size": 176981
    },
    {
      "filePath": "/assets/image (9).jpg",
      "fileName": "image (9).jpg",
      "ext": ".jpg",
      "size": 18977
    },
    {
      "filePath": "/assets/iv-drip-vitamin-infusion-therapy.jpg",
      "fileName": "iv-drip-vitamin-infusion-therapy.jpg",
      "ext": ".jpg",
      "size": 1238207
    },
    {
      "filePath": "/assets/loving-husband-hugging-pregnant-wifes-belly-male-hands-big-tummy-love-parenthood-pregnancy-concept.jpg",
      "fileName": "loving-husband-hugging-pregnant-wifes-belly-male-hands-big-tummy-love-parenthood-pregnancy-concept.jpg",
      "ext": ".jpg",
      "size": 13988576
    },
    {
      "filePath": "/assets/Mitochiondrien 3.jpg",
      "fileName": "Mitochiondrien 3.jpg",
      "ext": ".jpg",
      "size": 111539
    },
    {
      "filePath": "/assets/mitochondrien-befund, laktat.jpg",
      "fileName": "mitochondrien-befund, laktat.jpg",
      "ext": ".jpg",
      "size": 87000
    },
    {
      "filePath": "/assets/Mitochondrium 2.jpg",
      "fileName": "Mitochondrium 2.jpg",
      "ext": ".jpg",
      "size": 103086
    },
    {
      "filePath": "/assets/person-doing-yoga-pilates.jpg",
      "fileName": "person-doing-yoga-pilates.jpg",
      "ext": ".jpg",
      "size": 15741857
    },
    {
      "filePath": "/assets/photo_2026-06-24_14-17-08.jpg",
      "fileName": "photo_2026-06-24_14-17-08.jpg",
      "ext": ".jpg",
      "size": 138664
    },
    {
      "filePath": "/assets/Praxisbilder/Büro mit Menschen-min.jpg",
      "fileName": "Büro mit Menschen-min.jpg",
      "ext": ".jpg",
      "size": 1997538
    },
    {
      "filePath": "/assets/Praxisbilder/cosMedea Fensteransicht-min.jpg",
      "fileName": "cosMedea Fensteransicht-min.jpg",
      "ext": ".jpg",
      "size": 1752802
    },
    {
      "filePath": "/assets/Praxisbilder/cosMedea Flur-min.jpg",
      "fileName": "cosMedea Flur-min.jpg",
      "ext": ".jpg",
      "size": 2596325
    },
    {
      "filePath": "/assets/Praxisbilder/cosMedea Türansicht-min.jpg",
      "fileName": "cosMedea Türansicht-min.jpg",
      "ext": ".jpg",
      "size": 1487081
    },
    {
      "filePath": "/assets/Praxisbilder/feminatalis-Raum Fensteransicht-min.jpg",
      "fileName": "feminatalis-Raum Fensteransicht-min.jpg",
      "ext": ".jpg",
      "size": 1527604
    },
    {
      "filePath": "/assets/Praxisbilder/Hauseinhang-min.jpg",
      "fileName": "Hauseinhang-min.jpg",
      "ext": ".jpg",
      "size": 3460098
    },
    {
      "filePath": "/assets/Praxisbilder/Kursraum Ansicht aus dem Flur-min.jpg",
      "fileName": "Kursraum Ansicht aus dem Flur-min.jpg",
      "ext": ".jpg",
      "size": 4611658
    },
    {
      "filePath": "/assets/Praxisbilder/Kurstraum Matten Abendstimmung-min.jpg",
      "fileName": "Kurstraum Matten Abendstimmung-min.jpg",
      "ext": ".jpg",
      "size": 2161404
    },
    {
      "filePath": "/assets/Praxisbilder/Labor-min.jpg",
      "fileName": "Labor-min.jpg",
      "ext": ".jpg",
      "size": 1804480
    },
    {
      "filePath": "/assets/Praxisbilder/Seminarraum mit Leinwand-min.jpg",
      "fileName": "Seminarraum mit Leinwand-min.jpg",
      "ext": ".jpg",
      "size": 3325831
    },
    {
      "filePath": "/assets/Praxisbilder/Seminarraum mit Tischen -min.jpg",
      "fileName": "Seminarraum mit Tischen -min.jpg",
      "ext": ".jpg",
      "size": 3114202
    },
    {
      "filePath": "/assets/pregnant-woman-her-husband-hand-showing-heart-shape.jpg",
      "fileName": "pregnant-woman-her-husband-hand-showing-heart-shape.jpg",
      "ext": ".jpg",
      "size": 16423909
    },
    {
      "filePath": "/assets/Schwangere Vitalsstoffversorgung 2.PNG",
      "fileName": "Schwangere Vitalsstoffversorgung 2.PNG",
      "ext": ".PNG",
      "size": 47533
    },
    {
      "filePath": "/assets/top-view-pregnant-woman-bed-preparing-baby-clothes-home-writing-list-things-notebook-pregnancy-birth-concept.jpg",
      "fileName": "top-view-pregnant-woman-bed-preparing-baby-clothes-home-writing-list-things-notebook-pregnancy-birth-concept.jpg",
      "ext": ".jpg",
      "size": 7122530
    },
    {
      "filePath": "/brainlight-chair-beige.jpg",
      "fileName": "brainlight-chair-beige.jpg",
      "ext": ".jpg",
      "size": 53724
    },
    {
      "filePath": "/brainlight-chair-black.jpg",
      "fileName": "brainlight-chair-black.jpg",
      "ext": ".jpg",
      "size": 29503
    },
    {
      "filePath": "/brainlight-hero.jpg",
      "fileName": "brainlight-hero.jpg",
      "ext": ".jpg",
      "size": 50179
    },
    {
      "filePath": "/fuenf-elemente-diagramm.png",
      "fileName": "fuenf-elemente-diagramm.png",
      "ext": ".png",
      "size": 137637
    },
    {
      "filePath": "/healthy_fats_blog_hero.png",
      "fileName": "healthy_fats_blog_hero.png",
      "ext": ".png",
      "size": 959840
    },
    {
      "filePath": "/hebammen_section.png",
      "fileName": "hebammen_section.png",
      "ext": ".png",
      "size": 738098
    },
    {
      "filePath": "/hebammenpraxis_hero.png",
      "fileName": "hebammenpraxis_hero.png",
      "ext": ".png",
      "size": 710538
    },
    {
      "filePath": "/kinderwunsch_section.png",
      "fileName": "kinderwunsch_section.png",
      "ext": ".png",
      "size": 747112
    },
    {
      "filePath": "/logo.png",
      "fileName": "logo.png",
      "ext": ".png",
      "size": 74077
    },
    {
      "filePath": "/moxa-box.png",
      "fileName": "moxa-box.png",
      "ext": ".png",
      "size": 234705
    },
    {
      "filePath": "/moxa-zigarre.png",
      "fileName": "moxa-zigarre.png",
      "ext": ".png",
      "size": 133885
    },
    {
      "filePath": "/pulsdiagnostik.png",
      "fileName": "pulsdiagnostik.png",
      "ext": ".png",
      "size": 97784
    },
    {
      "filePath": "/schroepfen-blutig.png",
      "fileName": "schroepfen-blutig.png",
      "ext": ".png",
      "size": 56370
    },
    {
      "filePath": "/schroepfen-feuer.png",
      "fileName": "schroepfen-feuer.png",
      "ext": ".png",
      "size": 145715
    },
    {
      "filePath": "/suction-cups-therapy-session-close-up.jpg",
      "fileName": "suction-cups-therapy-session-close-up.jpg",
      "ext": ".jpg",
      "size": 1668993
    },
    {
      "filePath": "/zungendiagnostik.png",
      "fileName": "zungendiagnostik.png",
      "ext": ".png",
      "size": 217700
    }
  ]
};

export default assetImages;
